### ISSUE TITLE
Docs link is broken?

### ISSUE THREAD

**Issue by lurch** [product-os/contrato#19]
On https://github.com/balena-io/contrato/blob/master/README.md there's a "Documentation" link which points to https://balena-io.github.io/contrato/
When I visit that page, it doesn't contain any documentation itself, but it _does_ have another "Documentation" link which points to https://resin-io-modules.github.io/contrato/ - except when I click on **that** link I get a 404 error :confused:

**Comment by mehalter** [comment]
This has been made more clear with new documentation (https://product-os.github.io/contrato/modules/contrato.html)
